name: Update Streak Stats

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Streak Stats
        run: |
          mkdir -p dist
          curl -o dist/streak.svg "https://streak-stats.demolab.com?user=mrw-wq&theme=rose_pine&timezone=Africa/Nairobi&cache_seconds=1"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/streak.svg -f
          git commit -m "Updated streak stats" || exit 0
          git push
